
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kscope.kubecrunch.com
  resources:
  - linearlyindependentpaths
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kscope.kubecrunch.com
  resources:
  - linearlyindependentpaths/status
  verbs:
  - get
  - update
  - patch
