// +build !ignore_autogenerated

/*
Copyright 2019 cskkman@gmail.com.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// autogenerated by controller-gen object, do not modify manually

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscopePreservedFields) DeepCopyInto(out *KscopePreservedFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscopePreservedFields.
func (in *KscopePreservedFields) DeepCopy() *KscopePreservedFields {
	if in == nil {
		return nil
	}
	out := new(KscopePreservedFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscopeRequest) DeepCopyInto(out *KscopeRequest) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscopeRequest.
func (in *KscopeRequest) DeepCopy() *KscopeRequest {
	if in == nil {
		return nil
	}
	out := new(KscopeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscopeResponse) DeepCopyInto(out *KscopeResponse) {
	*out = *in
	if in.ExpectedFields != nil {
		in, out := &in.ExpectedFields, &out.ExpectedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscopeResponse.
func (in *KscopeResponse) DeepCopy() *KscopeResponse {
	if in == nil {
		return nil
	}
	out := new(KscopeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscopeStage) DeepCopyInto(out *KscopeStage) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	in.Response.DeepCopyInto(&out.Response)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscopeStage.
func (in *KscopeStage) DeepCopy() *KscopeStage {
	if in == nil {
		return nil
	}
	out := new(KscopeStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearlyIndependentPath) DeepCopyInto(out *LinearlyIndependentPath) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearlyIndependentPath.
func (in *LinearlyIndependentPath) DeepCopy() *LinearlyIndependentPath {
	if in == nil {
		return nil
	}
	out := new(LinearlyIndependentPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinearlyIndependentPath) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearlyIndependentPathList) DeepCopyInto(out *LinearlyIndependentPathList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinearlyIndependentPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearlyIndependentPathList.
func (in *LinearlyIndependentPathList) DeepCopy() *LinearlyIndependentPathList {
	if in == nil {
		return nil
	}
	out := new(LinearlyIndependentPathList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinearlyIndependentPathList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearlyIndependentPathSpec) DeepCopyInto(out *LinearlyIndependentPathSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]KscopeStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearlyIndependentPathSpec.
func (in *LinearlyIndependentPathSpec) DeepCopy() *LinearlyIndependentPathSpec {
	if in == nil {
		return nil
	}
	out := new(LinearlyIndependentPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearlyIndependentPathStatus) DeepCopyInto(out *LinearlyIndependentPathStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearlyIndependentPathStatus.
func (in *LinearlyIndependentPathStatus) DeepCopy() *LinearlyIndependentPathStatus {
	if in == nil {
		return nil
	}
	out := new(LinearlyIndependentPathStatus)
	in.DeepCopyInto(out)
	return out
}
